version: "3.9"
services:
  web:
    container_name: web
    build: .
    image: nginx:latest
    ports:
      - 81:81
    volumes:
      - ./assets/index.html:/etc/nginx/html/index.html:cached
      - ./assets:/etc/nginx/html/assets:cached
      - ./nginx.local:/etc/nginx/nginx.conf:cached
    links:
      - api
    extra_hosts:
      - "host.docker.internal:host-gateway"
  vm:
    container_name: vm
    build: ./docker/vm

  api:
    container_name: api
    build: api
    environment:
      - PORT=8001
    ports:
      - 8001:8001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    develop:
      watch:
        - action: rebuild
          path: api
          target: /app/api
          ignore:
            - node_modules/
  wsapi:
    container_name: wsapi
    build: ./api
    environment:
      - PORT=7001
    ports:
      - 7001:7001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: node wsserver.js
