version: "3.9"
services:
  web:
    container_name: web
    image: nginx:latest
    ports:
      - 81:5100
    volumes:
      - ./api/assets:/etc/nginx/html/:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - api
    extra_hosts:
      - "host.docker.internal:host-gateway"
  vm:
    container_name: vm
    build: ./docker/vm

  api:
    container_name: api
    build: ./api
    environment:
      - PORT=8001
    ports:
      - 8001:8001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    develop:
      watch:
        - path: ./api/index.html
          target: /app/api/index.html
          action: sync

  wsapi:
    container_name: wsapi
    build: ./api
    environment:
      - PORT=9000
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: node wsserver.js
