version: "3.9"
services:
  vm:
    container_name: vm
    build: ./docker/vm
  api:
    container_name: api
    build: api
    environment:
      - PORT=8001
    ports:
      - 8001:8001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    extra_hosts:
      - "host.docker.internal:host-gateway"
  wsapi:
    container_name: wsapi
    build: ./api
    environment:
      - PORT=7001
    ports:
      - 7001:7001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: node wsserver.js
