version: "3.9"
services:
  vm:
    container_name: vm
    build: ./docker/vm
  api:
    container_name: api
    build: .
    environment:
      - PORT=8001
    ports:
      - 8001:8001
    volumes:
      - db-data:/var/storages/sendit-ide
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  db-data: