---
name: "deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Run Tests
        run: npm test

      - name: Run End to End Tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build --if-present
          start: npm start

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://dokku@ide.sendit.dannluciano.com.br:22/sendit-ide"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          branch: "main"

      - name: Run commands after deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ide.sendit.dannluciano.com.br
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/sendit-ide/
            git pull --rebase
            docker compose build vm
